name: ${project.name}
description: ${project.description}
main: org.retromc.discordcore.v5.DiscordCorePlugin
version: ${project.version}
authors:
  - JohnyMuffin

commands:
  discordcore:
    description: Return information about the JDA bot.
    usage: /<command> [args]

permissions:
  discordcore.command:
    description: Permission to use the /discordcore command.
    default: true